name: Build Windows 7 Compatible EXE

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install pyinstaller pyodbc pandas Pillow PySide6

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconsole --onefile --clean ^
        --hidden-import=pyodbc ^
        --hidden-import=pandas ^
        --hidden-import=PIL ^
        --hidden-import=PySide6 ^
        كامل.py

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows7-Compatible-EXE
        path: dist/كامل.exe
