name: Build EXE for Windows

on:
  push:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller pyodbc PySide6

      - name: Build EXE
        run: |
          pyinstaller --noconsole --hidden-import=pyodbc --hidden-import=PySide6 --onefile main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: exe-file
          path: dist/main.exe
